outdir: ./output/
sample: FCAImmP7241240
cellranger_dir: ./input/FCAImmP7241240
metadata_file: ./input/old_raw_metadata.csv
load_raw_out: rawdata.h5ad
load_meta_out: loaddata.h5ad #should this be defined here? or in script.py?

args:
  soupx:
    soupx_output_dir: "soupx"
  load_mtx:
    adata_filename: "adata.h5ad"
  scrublet_output_dir: "scrublet"
  scanpy_output_dir: "scanpy"
  filter_reads_output_dir: "filter_reads"
  feature_selection_output_dir: "feature_selection"
  html_output_dir: "html"
  dimensionality_output_dir: "dimensionality"
