name: sc-analysis-nf
channels:
  - bioconda
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - anndata=0.9.2
  - fire==0.5.0
  - ipykernel=6.26.0
  - ipython=8.12.2
  - jinja2=3.1.2
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - leidenalg=0.10.1
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - matplotlib-inline=0.1.6
  - numpy=1.24.4
  - pandas=2.0.3
  - pillow=10.1.0
  - pip=23.3.1
  - python=3.8.18
  - scanpy=1.9.5
  - scikit-learn=1.3.2
  - scikit-sparse=0.4.12
  - scipy=1.10.1
  - scrublet=0.2.3
  - scvi=0.6.8
  - seaborn=0.13.0
  - seaborn-base=0.13.0
